### PR TITLE
Adding dl2 dataset for sensitivity tests 

### PR DESCRIPTION
**Pull request by vuillaut**
Hi

This adds the dl2 dataset and makes sure it is created before the test requiring it.

### CODE REVIEW

**Comment by vuillaut** [comment]
I don't quite understand why the commits from Franca appear here though 🤔 
Were you not synched with ctapipe master on this dev branch?

**Comment by rlopezcoto** [comment]
Mmm... no idea, my `tests_sensitivity` branch does not have those commits merged yet, I guess that you merged them in your branch and when committing to my outdated branch they appear?

**Comment by rlopezcoto** [comment]
Not sure if it is a good idea to merge this directly to my PR, it may mess things up

**Comment by vuillaut** [comment]
> Mmm... no idea, my `tests_sensitivity` branch does not have those commits merged yet, I guess that you merged them in your branch and when committing to my outdated branch they appear?

Could you try synching master into your branch please?

**Pull request closed without merging**
